version: "3.8"

networks:
  tech-challenge:
    driver: bridge

services:
  pedidos-mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - tech-challenge
    ports:
      - 27070:27017
    restart: always
